apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb1
  name: myweb1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    country: India
  type: NodePort
status:
  loadBalancer: {}
